services:
  dev:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8031 --reload
    image: csc_tickets_api
    container_name: csc-tickets-api
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8031:8031
    environment:
      - ENVIRONMENT=dev
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8031/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
  
  